language: node_js
node_js: stable
cache:
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - git submodule update --init
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master
    target_branch: gh-pages
  